<?php

declare(strict_types=1);

/**
 * One kept Roster Change Form (Phase 11, spec-v2 §12): its header as it
 * was printed, its lines, and where each line has got to.
 *
 * Four things, in the order they are used:
 *
 *   * the header, and Download again — the same file, byte for byte;
 *   * the progress, and the two one-tap buttons: "every line went to the
 *     Division Chairman today", "every line went to Rosters today". They
 *     fill only the lines that have no date yet, so they are safe to press
 *     twice and safe to press after one line was dated by hand;
 *   * the tracking table: the RCF number and the two dates on every line,
 *     with a whole-form row above them that wins over the lines below —
 *     one save numbers a whole form, and a line can still be the exception;
 *   * "In the roster", which is not typed by anybody: it is read out of
 *     what the imports since have done (RcfTracking::landed()).
 *
 * Everybody who can open this form can track it (RcfTracking::mayView), so
 * the controls are never hidden from a viewer. Every rendered value goes
 * through e().
 *
 * @var Rerm\App                             $app
 * @var Rerm\Auth\User                       $user
 * @var array<int, array{0:string,1:string}> $notices
 * @var array<string, mixed>                 $rcf   form and rows — RcfTracking::one()'s answer
 */

use Rerm\Csrf;
use Rerm\Forms\RcfTracking;
use Rerm\View;

$form = $rcf['form'];
$rows = $rcf['rows'];

$number = static fn (int $n): string => number_format($n);
$action = $app->url('rcf?id=' . (int) $form['id']);

/** A stored DATE as the day it names, in words. PLAIN; the caller escapes. */
$day = static function (?string $iso): string {
    if ($iso === null || $iso === '') {
        return '';
    }
    $parsed = DateTimeImmutable::createFromFormat('!Y-m-d', $iso);

    return $parsed instanceof DateTimeImmutable ? $parsed->format('j M Y') : $iso;
};

$fraction = static function (int $n, int $of): string {
    $class = $n === 0 ? 'chip-muted' : ($n < $of ? 'chip-warn' : 'chip-ok');

    return '<span class="chip ' . $class . '">' . e((string) $n) . ' of ' . e((string) $of) . '</span>';
};

$steps = RcfTracking::STEPS;
?>
<p class="hint"><a href="<?= e($app->url('rcfs')) ?>">&larr; Track RCFs</a></p>

<h1>Roster Change Form &mdash; <?= e((string) $form['subcommittee']) ?></h1>
<p class="lede">
    Submitted by <?= e((string) $form['submitter']) ?>, dated <?= e($day((string) $form['form_date'])) ?>
    &middot; RODEO <?= e((string) $form['year_label']) ?>
    &middot; <?= e($number((int) $form['rows'])) ?> <?= (int) $form['rows'] === 1 ? 'person' : 'people' ?>
    &middot; generated by <?= e((string) $form['generator_name']) ?>
    <?= View::time($app, (string) $form['generated_at']) ?>
</p>

<div class="cards">
    <div class="card">
        <h2>Where it has got to</h2>
        <dl class="facts">
            <dt>RCF number</dt>
            <dd><?= $fraction((int) $form['numbered'], (int) $form['rows']) ?><?php
                if ($form['serials'] !== []) { ?> <span class="mono"><?= e(implode(', ', $form['serials'])) ?></span><?php } ?></dd>
            <dt>To the Division Chairman</dt>
            <dd><?= $fraction((int) $form['dc'], (int) $form['rows']) ?></dd>
            <dt>To Rosters</dt>
            <dd><?= $fraction((int) $form['rosters'], (int) $form['rows']) ?></dd>
            <dt>In the roster</dt>
            <dd><?= $fraction((int) $form['landed'], (int) $form['rows']) ?>
                <span class="why">read from the imports since; never typed</span></dd>
        </dl>
        <?php /* The one-tap case: the form went, all of it, today. Each
                 button is its own form so pressing one never submits the
                 table below half filled in. */ ?>
        <?php foreach ($steps as $key => [$column, $label]) { ?>
            <form method="post" action="<?= e($action) ?>" class="today">
                <?= Csrf::field() ?>
                <input type="hidden" name="id" value="<?= e((string) $form['id']) ?>">
                <button type="submit" name="action" value="<?= e($key) ?>_today" class="quiet">
                    <?= e($label) ?> today &mdash; every line not yet dated
                </button>
            </form>
        <?php } ?>
    </div>

    <div class="card">
        <h2>Download it again</h2>
        <p>
            The same spreadsheet, rebuilt from what was printed the first time
            &mdash; not from the roster as it stands now, which the form may
            since have changed.
            <?php if ((int) $form['regenerated_count'] > 0) { ?>
                Downloaded again <?= e($number((int) $form['regenerated_count'])) ?>
                <?= (int) $form['regenerated_count'] === 1 ? 'time' : 'times' ?>, last
                <?= View::time($app, (string) $form['last_regenerated_at']) ?>.
            <?php } ?>
        </p>
        <form method="post" action="<?= e($action) ?>">
            <?= Csrf::field() ?>
            <input type="hidden" name="id" value="<?= e((string) $form['id']) ?>">
            <span class="chip chip-warn">This file is personal data</span>
            <p class="hint">It leaves this server the moment you download it, and the download is logged with your name.</p>
            <button type="submit" name="action" value="download">Download the form again</button>
        </form>
    </div>
</div>

<h2>The lines, and their tracking</h2>
<form method="post" action="<?= e($action) ?>" class="tracking">
    <?= Csrf::field() ?>
    <input type="hidden" name="id" value="<?= e((string) $form['id']) ?>">
    <input type="hidden" name="action" value="track">

    <table class="rcf-track">
        <caption>
            Fill the <strong>Every line</strong> row to set the whole form at
            once &mdash; it wins over the lines below it. Leave it blank to change
            lines one at a time; a date box emptied clears that date. The RCF
            number is the Division Chairman&rsquo;s, from the box marked
            &ldquo;DC use only&rdquo; on their numbered form.
        </caption>
        <thead><tr>
            <th scope="col"><span class="vh">Row</span>#</th>
            <th scope="col">Member</th>
            <th scope="col">Change</th>
            <th scope="col">RCF #</th>
            <th scope="col">To the DC</th>
            <th scope="col">To Rosters</th>
            <th scope="col">In the roster</th>
        </tr></thead>
        <tbody>
            <tr class="all">
                <td class="n" data-label="Row">All</td>
                <td data-label="Member"><strong>Every line</strong></td>
                <td data-label="Change"><span class="why">wins over the lines below</span></td>
                <td data-label="RCF #"><input type="text" name="track[all][serial]" maxlength="<?= e((string) RcfTracking::SERIAL_MAX) ?>"
                    aria-label="RCF number, every line" autocomplete="off" placeholder="every line"></td>
                <?php foreach ($steps as $key => [$column, $label]) { ?>
                    <td data-label="<?= e($key === 'dc' ? 'To the DC' : 'To Rosters') ?>"><input type="date" name="track[all][<?= e($key) ?>]"
                        aria-label="<?= e($label) ?>, every line"></td>
                <?php } ?>
                <td data-label="In the roster"><span class="why">&mdash;</span></td>
            </tr>
        <?php foreach ($rows as $line) { $id = (int) $line['id']; $n = (int) $line['position']; ?>
            <tr>
                <td class="n" data-label="Row"><?= e((string) $n) ?>)</td>
                <td data-label="Member">
                    <?php if ($line['member_id'] !== null) { ?>
                        <a href="<?= e($app->url('member?id=' . (int) $line['member_id'] . '&from=rcf&back=' . rawurlencode('id=' . (int) $form['id']))) ?>"><?= e((string) $line['member_name']) ?></a>
                    <?php } else { ?>
                        <?= e((string) $line['member_name']) ?>
                    <?php } ?>
                    <?php if ((string) $line['member_number'] !== '') { ?><span class="why mono"><?= e((string) $line['member_number']) ?></span><?php } ?>
                    <?php if ($line['rookie']) { ?><span class="why">rookie</span><?php } ?>
                    <?php if ($line['wait_list']) { ?><span class="why">wait list</span><?php } ?>
                </td>
                <td data-label="Change"><?= e((string) $line['change']) ?><?php
                    if ((string) $line['sponsor'] !== '') { ?> <span class="why">&middot; <?= e((string) $line['sponsor']) ?></span><?php } ?></td>
                <td data-label="RCF #"><input type="text" name="track[<?= $id ?>][serial]" maxlength="<?= e((string) RcfTracking::SERIAL_MAX) ?>"
                    aria-label="RCF number, row <?= $n ?>" autocomplete="off"<?=
                    (string) $line['serial'] === '' ? '' : ' value="' . e((string) $line['serial']) . '"' ?>></td>
                <?php foreach ($steps as $key => [$column, $label]) { ?>
                    <td data-label="<?= e($key === 'dc' ? 'To the DC' : 'To Rosters') ?>"><input type="date" name="track[<?= $id ?>][<?= e($key) ?>]"
                        aria-label="<?= e($label) ?>, row <?= $n ?>"<?=
                        $line[$column] === null ? '' : ' value="' . e((string) $line[$column]) . '"' ?>></td>
                <?php } ?>
                <td data-label="In the roster"><?php if ($line['landed'] === null) { ?>
                        <span class="chip chip-muted">not yet</span>
                        <?php if ((string) $line['member_number'] === '') { ?><span class="why">no member number to watch for</span><?php } ?>
                    <?php } else { ?>
                        <span class="chip chip-ok">yes</span>
                        <span class="why">import of <?= View::time($app, (string) $line['landed']['at']) ?></span>
                    <?php } ?>
                    <?php if ($line['tracked_at'] !== null) { ?>
                        <span class="why">tracked by <?= e((string) $line['tracked_by_name']) ?> <?= View::time($app, (string) $line['tracked_at']) ?></span>
                    <?php } ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>

    <button type="submit">Save the tracking</button>
</form>

<p><a href="<?= e($app->url('rcfs')) ?>">&larr; Track RCFs</a></p>
