<?php

declare(strict_types=1);

/**
 * Track RCFs (Phase 11, spec-v2 §12) — every Roster Change Form made here,
 * and where each line of it has got to.
 *
 * Three parts, in the order somebody arrives needing them:
 *
 *   * a search box, because the question that brought this screen into
 *     being is about ONE member — "was an RCF ever submitted for them" —
 *     and it is asked with a phone in one hand;
 *   * the caller's own forms, newest first, each with how many of its lines
 *     have gone to the Division Chairman, to Rosters, and into the roster;
 *   * for an Executive Officer, everybody else's, paged — the Chairman is
 *     copied on every form and this is the pile of emails, sorted.
 *
 * Read-only here: the tracking is written on the form's own page. The only
 * controls are the search box and links, so there is no POST and no CSRF
 * check to forget. Every rendered value goes through e().
 *
 * @var Rerm\App                             $app
 * @var Rerm\Auth\User                       $user
 * @var array<int, array{0:string,1:string}> $notices
 * @var array<string, mixed>                 $tracking mine, others, search — RcfTracking's answers
 */

use Rerm\View;

$number = static fn (int $n): string => number_format($n);

/** A stored DATE as the day it names, in words. PLAIN; the caller escapes. */
$day = static function (?string $iso): string {
    if ($iso === null || $iso === '') {
        return '';
    }
    $parsed = DateTimeImmutable::createFromFormat('!Y-m-d', $iso);

    return $parsed instanceof DateTimeImmutable ? $parsed->format('j M Y') : $iso;
};

/**
 * "3 of 3" as a chip whose colour says whether the step is done, part done
 * or not started — always with the numbers, never the hue alone (spec 8.3).
 */
$fraction = static function (int $n, int $of): string {
    $class = $n === 0 ? 'chip-muted' : ($n < $of ? 'chip-warn' : 'chip-ok');

    return '<span class="chip ' . $class . '">' . e((string) $n) . ' of ' . e((string) $of) . '</span>';
};

/** A link into this screen with the parameters it understands and no others. */
$href = static function (array $params) use ($app): string {
    $params = array_filter($params, static fn (mixed $v): bool => $v !== null && $v !== '' && $v !== 0 && $v !== 1);
    $query  = http_build_query($params);

    return $app->url('rcfs') . ($query === '' ? '' : '?' . $query);
};

$open = static fn (int $id): string => $app->url('rcf?id=' . $id);

/** One form as a table row — the same columns for mine and for everyone's. */
$formRow = static function (array $form, bool $withGenerator) use ($app, $open, $fraction, $day): void {
    ?><tr>
        <td data-label="Generated"><a href="<?= e($open((int) $form['id'])) ?>"><?= View::time($app, (string) $form['generated_at']) ?></a>
            <span class="why">form dated <?= e($day((string) $form['form_date'])) ?></span></td>
        <?php if ($withGenerator) { ?>
            <td data-label="Generated by"><?= e((string) $form['generator_name']) ?></td>
        <?php } ?>
        <td data-label="Sub-committee"><?= e((string) $form['subcommittee']) ?>
            <span class="why"><?= e((string) $form['year_label']) ?></span></td>
        <td class="num" data-label="People"><?= e((string) $form['rows']) ?></td>
        <td data-label="RCF #"><?php
            if ($form['serials'] === []) { ?><span class="chip chip-muted">not yet</span><?php }
            else { ?><span class="mono"><?= e(implode(', ', $form['serials'])) ?></span><?php } ?></td>
        <td data-label="To the DC"><?= $fraction((int) $form['dc'], (int) $form['rows']) ?></td>
        <td data-label="To Rosters"><?= $fraction((int) $form['rosters'], (int) $form['rows']) ?></td>
        <td data-label="In the roster"><?= $fraction((int) $form['landed'], (int) $form['rows']) ?></td>
    </tr><?php
};

$search = $tracking['search'];
$others = $tracking['others'];
?>
<h1>Track RCFs</h1>
<p class="lede">
    Every Roster Change Form made here is kept, so it can be downloaded again
    and so the question &ldquo;was an RCF ever submitted for this member, and
    where did it stop&rdquo; is answered here instead of in a pile of emails.
    A form goes to the Division Chairman, who numbers it and sends it to
    Rosters; the next roster import shows whether it was processed.
</p>

<form class="quick find" method="get" action="<?= e($app->url('rcfs')) ?>">
    <label for="member">Find a member on any form</label>
    <input type="search" id="member" name="member" value="<?= e((string) $search['q']) ?>"
           placeholder="Member number, or part of a name" autocomplete="off" inputmode="search">
    <button type="submit" class="quiet">Find them</button>
    <?php if ($search['too_short']) { ?>
        <p class="hint">Type at least <?= e((string) Rerm\Forms\RcfTracking::SEARCH_MIN_CHARS) ?> characters.</p>
    <?php } ?>
</form>

<?php if ((string) $search['q'] !== '' && !$search['too_short']) { ?>
    <?php if ($search['matches'] === []) { ?>
        <div class="card">
            <h2>Nobody matches &ldquo;<?= e((string) $search['q']) ?>&rdquo;</h2>
            <p>
                No line on any form you can see names them. A form made before
                this build is not here &mdash; only forms made since are kept
                &mdash; and a member typed in by name alone is found by that name,
                not by a number.
            </p>
        </div>
    <?php } else { ?>
        <h2><?= e($number(count($search['matches']))) ?>
            <?= count($search['matches']) === 1 ? 'line names' : 'lines name' ?>
            &ldquo;<?= e((string) $search['q']) ?>&rdquo;</h2>
        <table class="track">
            <caption>Newest form first. Open the form to change its tracking.</caption>
            <thead><tr>
                <th scope="col">Form</th>
                <th scope="col">Member</th>
                <th scope="col">Change</th>
                <th scope="col">RCF #</th>
                <th scope="col">To the DC</th>
                <th scope="col">To Rosters</th>
                <th scope="col">In the roster</th>
            </tr></thead>
            <tbody>
            <?php foreach ($search['matches'] as $line) { ?>
                <tr>
                    <td data-label="Form"><a href="<?= e($open((int) $line['rcf_id'])) ?>"><?= View::time($app, (string) $line['generated_at']) ?></a>
                        <span class="why"><?= e((string) $line['subcommittee']) ?> &middot; by <?= e((string) $line['generator_name']) ?></span></td>
                    <td data-label="Member"><?= e((string) $line['member_name']) ?>
                        <?php if ((string) $line['member_number'] !== '') { ?><span class="why mono"><?= e((string) $line['member_number']) ?></span><?php } ?></td>
                    <td data-label="Change"><?= e((string) $line['change']) ?></td>
                    <td data-label="RCF #"><?= (string) $line['serial'] === '' ? '<span class="chip chip-muted">not yet</span>' : '<span class="mono">' . e((string) $line['serial']) . '</span>' ?></td>
                    <td data-label="To the DC"><?= $line['sent_to_dc_on'] === null ? '<span class="chip chip-muted">not yet</span>' : e($day($line['sent_to_dc_on'])) ?></td>
                    <td data-label="To Rosters"><?= $line['sent_to_rosters_on'] === null ? '<span class="chip chip-muted">not yet</span>' : e($day($line['sent_to_rosters_on'])) ?></td>
                    <td data-label="In the roster"><?= $line['landed'] === null
                        ? '<span class="chip chip-muted">not yet</span>'
                        : '<span class="chip chip-ok">yes</span> <span class="why">import of ' . View::time($app, (string) $line['landed']['at']) . '</span>' ?></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    <?php } ?>
<?php } ?>

<h2>Your RCFs</h2>
<?php if ($tracking['mine'] === []) { ?>
    <div class="card">
        <p>
            You have not made a Roster Change Form since this build. The next one
            you download from <a href="<?= e($app->url('form-rcf')) ?>">Create Forms</a>
            will appear here, with its lines ready to track.
        </p>
    </div>
<?php } else { ?>
    <table class="track">
        <caption>
            Newest first. Each step counts the form&rsquo;s lines: how many have
            an RCF number, how many went to the Division Chairman, how many to
            Rosters, and how many the roster now shows. Open a form to change any
            of it or to download it again.
        </caption>
        <thead><tr>
            <th scope="col">Generated</th>
            <th scope="col">Sub-committee</th>
            <th scope="col" class="num">People</th>
            <th scope="col">RCF #</th>
            <th scope="col">To the DC</th>
            <th scope="col">To Rosters</th>
            <th scope="col">In the roster</th>
        </tr></thead>
        <tbody>
        <?php foreach ($tracking['mine'] as $form) { $formRow($form, false); } ?>
        </tbody>
    </table>
<?php } ?>

<?php if ($others !== null) { ?>
    <h2>Everyone else&rsquo;s RCFs</h2>
    <p class="hint">
        Every form anybody else has made, with who made it. Open one to number
        its lines or mark them sent to Rosters.
    </p>
    <?php if ($others['forms'] === []) { ?>
        <div class="card"><p>Nobody else has made a Roster Change Form since this build.</p></div>
    <?php } else { ?>
        <table class="track">
            <thead><tr>
                <th scope="col">Generated</th>
                <th scope="col">Generated by</th>
                <th scope="col">Sub-committee</th>
                <th scope="col" class="num">People</th>
                <th scope="col">RCF #</th>
                <th scope="col">To the DC</th>
                <th scope="col">To Rosters</th>
                <th scope="col">In the roster</th>
            </tr></thead>
            <tbody>
            <?php foreach ($others['forms'] as $form) { $formRow($form, true); } ?>
            </tbody>
        </table>
        <p class="lede">
            <?= e($number((int) $others['total'])) ?>
            <?= (int) $others['total'] === 1 ? 'form' : 'forms' ?><?php
            if ((int) $others['pages'] > 1) { ?> &middot; page <?= e($number((int) $others['page'])) ?>
                of <?= e($number((int) $others['pages'])) ?><?php } ?>
        </p>
        <?php if ((int) $others['pages'] > 1) { ?>
            <nav class="toggle" aria-label="Forms">
                <?php if ((int) $others['page'] > 1) { ?>
                    <a href="<?= e($href(['member' => $search['q'], 'page' => (int) $others['page'] - 1])) ?>">&larr; Newer</a>
                <?php } ?>
                <?php if ((int) $others['page'] < (int) $others['pages']) { ?>
                    <a href="<?= e($href(['member' => $search['q'], 'page' => (int) $others['page'] + 1])) ?>">Older &rarr;</a>
                <?php } ?>
            </nav>
        <?php } ?>
    <?php } ?>
<?php } ?>

<p><a href="<?= e($app->url('forms')) ?>">Create Forms</a> &middot; <a href="<?= e($app->url('menu')) ?>">Menu</a></p>
